POST http://localhost:8082/api/admin/create-admin
{
    "email": "admin@admin.com",
    "password": "admin"
}

###
GET http://localhost:8082/api/dutystatus

###
POST  http://localhost:8082/api/drivers/signup-driver
{
  "firstName": "Isaac",
  "lastName": "Phiri",
  "licenseNumber": 1234567,
  "nationalId": "123456/12/1",
  "contactNumber": 1234567890,
  "email": "ice@gmail.com",
  "homeAddress": "Libala",
  "licenseExpiryDate": "2023",
  "password": "123456",
  "password_confirmation": "123456"
}

###
PUT http://localhost:8082/api/admin/64b40ca29b90196f352395f9
{
    "username": "admin@admin.com",
    "password": "admin"
}

###
DELETE http://localhost:8082/api/admin/64b40ca29b90196f352395f9

###
DELETE http://localhost:8082/api/drivers/64cf914bb0b971ededfd2cdf

###
DELETE http://localhost:8082/api/logentries/64a30c79f1bbad6659511d4e