GET http://localhost:8082/api/trips

####
GET http://localhost:8082/api/drivers


####
POST http://localhost:8082/api/auth/signup
Content-Type: application/json

{
    "firstName": "Zayon",
    "lastName": "Blue",
    "licenseNumber": 547936520,
    "nationalId": "672545/10/1",
    "contactNumber": 1237466369,
    "email": "zayonblue@gmail.com",
    "homeAddress": "Lusaka",
    "password": "green",
    "password_confirmation": "green",
    "licenseExpiryDate": "2027"
  }

####
POST http://localhost:8082/api/auth/signin
Content-Type: application/json
{
    "email": "ammy@gmail.com",
    "password": "qwerty"
}

####
DELETE http://localhost:8082/api/drivers/64a3096e70374a8919846207

####
GET http://localhost:8082/api/dutystatus